### ISSUE TITLE
components/cmulex/lex_data_include/cmu_lex_data_raw.c:2:4: error: expected identifier or '(' before numeric constant

### ISSUE THREAD

**Issue by Shallowmallow** [alkhimey/esp32-flite#1]
When I try to compile with esp32-idf  ( version 4. something ( I needed to add makelist to make it work))
I have this error
components/cmulex/lex_data_include/cmu_lex_data_raw.c:2:4: error: expected identifier or '(' before numeric constant

Do you know what can be the problem ?
Which version of esp-32 idf where you using ?

**Comment by Shallowmallow** [comment]
I had made a bad CMakeList

for cmulex, and it worked ( I had accidentaly put cmu_lex_data_raw.c as a SRC)
```
file(GLOB SOURCES *.c)
idf_component_register(SRCS ${SOURCES}
                       INCLUDE_DIRS "include" "lex_data_include"
			REQUIRES flite)
```

**Comment by jalakamkiranadspl** [comment]
Hello @Shallowmallow , have you ported the code to another version of ESP IDF. Can you please tell me the steps to do it so that I can replicate the same?
